name: C++ CI
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
env:
  BUILD_TYPE: Release

jobs:
  build-and-test-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y cmake ninja-build gcc-14 g++-14
    - name: gcc-14-release
      run: cmake --workflow --preset="ci-gcc-14-release"

  build-and-test-clang:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Add LLVM Repository
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19
        
    - name: Install dependencies
      run: |
           sudo apt-get update
           sudo apt-get install -y cmake g++-14 ninja-build clang-19 libfmt-dev libc++-19-dev libc++abi-19-dev

    - name: clang-release
      run: cmake --workflow --preset="ci-clang-release"
      
    - name: clang-libc++-release
      run: cmake --workflow --preset="ci-clang-libc++-release"
      
  build-and-test-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: ci-clangcl-release
      run: cmake --workflow --preset="ci-clangcl-release"
    - name: ci-msvc-release
      run: cmake --workflow --preset="ci-msvc-release"

